[package]
name = "leetcode-daily"
version = "0.1.0"
edition = "2021"

[dependencies]
# HTTP 客户端，用于调用 API
reqwest = { workspace = true }
# 序列化/反序列化工具
serde = { workspace = true }
serde_json = { workspace = true }
# 邮件发送库
lettre = { workspace = true }
# 错误处理简化工具
anyhow = { workspace = true }
# 时间处理
chrono = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
